{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.eztest",
    "module": "eztest-core",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "eztest-core-1.0.jar",
          "url": "eztest-core-1.0.jar",
          "size": 141847,
          "sha512": "7151bd90414fd5e4f9ecb840d7490844bff0974edfcd61a47f1a39cf84deed637bf5ecfd8dfd0bc94113d10f3305cb45534b19740734ea966430dd97808946ca",
          "sha256": "865b3bdb12148e41637f9bf7c1e77ab3c2a555314bdee722f8ca4603bf17794f",
          "sha1": "7e3b12e43792fac40b7be28f6a623e7fc00e6866",
          "md5": "46672fbaab279fcbe6c26025985d7b68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.14"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.15.Final"
          }
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.7.3"
          }
        },
        {
          "group": "org.spockframework",
          "module": "spock-core",
          "version": {
            "requires": "2.3-groovy-4.0"
          }
        },
        {
          "group": "commons-lang",
          "module": "commons-lang",
          "version": {
            "requires": "2.6"
          }
        }
      ],
      "files": [
        {
          "name": "eztest-core-1.0.jar",
          "url": "eztest-core-1.0.jar",
          "size": 141847,
          "sha512": "7151bd90414fd5e4f9ecb840d7490844bff0974edfcd61a47f1a39cf84deed637bf5ecfd8dfd0bc94113d10f3305cb45534b19740734ea966430dd97808946ca",
          "sha256": "865b3bdb12148e41637f9bf7c1e77ab3c2a555314bdee722f8ca4603bf17794f",
          "sha1": "7e3b12e43792fac40b7be28f6a623e7fc00e6866",
          "md5": "46672fbaab279fcbe6c26025985d7b68"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "eztest-core-1.0-javadoc.jar",
          "url": "eztest-core-1.0-javadoc.jar",
          "size": 261,
          "sha512": "0e31a0cae571cfd555689cd07bc37bb188ff22e9a11d4b957a20cf22fe537874fd402dda6fa3515c755e55113118e88ee10354b5c1b35a319747590ba0336f81",
          "sha256": "f937a666c3e9ea9adf8b0b20c4a9e5915589a6a0d129e89bf209a8e71b5a43a4",
          "sha1": "b5407598167312fd20d7e14b65dc2c83bcdb9e1a",
          "md5": "14031373929654a3206e260ea07f2078"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "eztest-core-1.0-sources.jar",
          "url": "eztest-core-1.0-sources.jar",
          "size": 36930,
          "sha512": "ec0356c606afd84a5b0ba6fdc137c14b37df284150eca7d2d52f6c3d7eef28fbe756a94c4a43fa8e8c79b0c4d1a95b01031a9b1026eae5dc888c88c0d23e6525",
          "sha256": "27c5bc147b57d29b380b38d9f61e875f102453946b821dd7f52c3b3dba8b347b",
          "sha1": "7c14b90d4c906b31fb2fc08c5899962ec9f1227a",
          "md5": "071ff4a1985ae0564910a14132048305"
        }
      ]
    }
  ]
}
