name: Build and Publish Java Package

on:
  push:
    branches:
      - master  # Set this to your default branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8.0'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '8.0'
          distribution: 'adopt'

      - name: Set Java tool options
        run: echo "JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew -i build

      - name: Read Version File
        id: version
        run: echo "::set-output name=VERSION::$(cat VERSION)"

      - name: Configure Git
        run: |
          git config --global user.email "github@aldsistemas.com.br"
          git config --global user.name "GitHub"

      - name: Clone releases branch
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
        run: |
          git checkout -b releases

      - name: Publish to Gradle
        run: ./gradlew -i publish

      - name: Commit and push release
        run: |
          cd build/repos/releases
          git add *
          git commit -m "[release] Commit release ${{ steps.version.outputs.VERSION }}"
          git push origin releases
